# Generated by Django 5.2.16 on 2026-07-28 04:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_observation_on_alert', models.BooleanField(default=True, verbose_name='exigir observación según la regla del producto')),
                ('generate_product_alerts', models.BooleanField(default=True, verbose_name='generar alertas por producto')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('daily_deadline', models.TimeField(default='21:00', verbose_name='hora límite inventario diario')),
                ('general_deadline', models.TimeField(default='21:00', verbose_name='hora límite inventario general')),
                ('general_frequency', models.CharField(choices=[('DIARIO', 'Diaria'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='SEMANAL', max_length=15, verbose_name='frecuencia inventario general')),
            ],
            options={
                'verbose_name': 'punto de venta',
                'verbose_name_plural': 'puntos de venta',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='categoría')),
                ('unidad_medida', models.CharField(choices=[('KG', 'Kilogramo'), ('UND', 'Unidad'), ('LITRO', 'Litro'), ('BOLSA', 'Bolsa'), ('PORCION', 'Porción'), ('GALON', 'Galón'), ('OTRA', 'Otra')], default='OTRA', max_length=10, verbose_name='unidad de medida')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('display_order', models.PositiveIntegerField(default=100, verbose_name='orden visual')),
                ('permite_decimales', models.BooleanField(default=True, verbose_name='permite decimales')),
                ('incluir_inventario_diario', models.BooleanField(default=False, verbose_name='incluir en inventario diario')),
                ('incluir_inventario_general', models.BooleanField(default=True, verbose_name='incluir en inventario general')),
                ('valor_unitario_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor unitario promedio')),
                ('observacion_costo', models.CharField(blank=True, max_length=250, verbose_name='observación de costo')),
                ('critical_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cantidad crítica')),
                ('minimum_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cantidad mínima')),
                ('maximum_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cantidad máxima')),
                ('require_observation_low', models.BooleanField(default=True, verbose_name='exigir observación en crítico o bajo')),
                ('require_observation_high', models.BooleanField(default=True, verbose_name='exigir observación en alto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('CREAR_INVENTARIO', 'Crear inventario'), ('GUARDAR_BORRADOR', 'Guardar borrador'), ('FINALIZAR_INVENTARIO', 'Finalizar inventario'), ('REABRIR_INVENTARIO', 'Reabrir inventario'), ('EDITAR_INVENTARIO', 'Editar inventario'), ('ANULAR_INVENTARIO', 'Anular inventario'), ('CREAR_PRODUCTO', 'Crear producto'), ('EDITAR_PRODUCTO', 'Editar producto'), ('ACTIVAR_PRODUCTO', 'Activar producto'), ('DESACTIVAR_PRODUCTO', 'Desactivar producto'), ('CAMBIAR_REGLAS', 'Cambiar reglas'), ('ATENDER_ALERTA', 'Atender alerta'), ('CAMBIAR_CONFIGURACION', 'Cambiar configuración')], max_length=30)),
                ('model', models.CharField(max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de inventario')),
                ('inventory_type', models.CharField(choices=[('DIARIO', 'Inventario diario'), ('GENERAL', 'Inventario general')], max_length=15, verbose_name='tipo')),
                ('state', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_PROGRESO', 'En progreso'), ('FINALIZADO', 'Finalizado'), ('FINALIZADO_CON_ALERTAS', 'Finalizado con alertas'), ('REABIERTO', 'Reabierto'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=30, verbose_name='estado')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='inicio')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='finalización')),
                ('total_expected', models.PositiveIntegerField(default=0)),
                ('total_counted', models.PositiveIntegerField(default=0)),
                ('total_critical', models.PositiveIntegerField(default=0)),
                ('total_low', models.PositiveIntegerField(default=0)),
                ('total_normal', models.PositiveIntegerField(default=0)),
                ('total_high', models.PositiveIntegerField(default=0)),
                ('general_observation', models.TextField(blank=True, verbose_name='observación general')),
                ('locked', models.BooleanField(default=False, verbose_name='bloqueado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories_modified', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories_reopened', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories_responsible', to=settings.AUTH_USER_MODEL)),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='inventarios.pointofsale')),
            ],
            options={
                'ordering': ['-inventory_date', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=30, verbose_name='código snapshot')),
                ('product_name', models.CharField(max_length=120, verbose_name='nombre snapshot')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='categoría snapshot')),
                ('unit', models.CharField(max_length=30, verbose_name='unidad snapshot')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cantidad contada')),
                ('critical_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('minimum_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_unitario_aplicado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('valor_total_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('require_observation_low_applied', models.BooleanField(default=True)),
                ('require_observation_high_applied', models.BooleanField(default=True)),
                ('result', models.CharField(choices=[('CRITICO', 'Crítico'), ('BAJO', 'Bajo'), ('NORMAL', 'Normal'), ('ALTO', 'Alto'), ('SIN_REGLA', 'Sin regla'), ('NO_CONTADO', 'No contado')], default='NO_CONTADO', max_length=20)),
                ('observation', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventarios.inventory')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items_registered', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarios.product')),
            ],
            options={
                'ordering': ['product__display_order', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('PRODUCTO_CRITICO', 'Producto crítico'), ('PRODUCTO_BAJO', 'Producto bajo'), ('PRODUCTO_ALTO', 'Producto alto'), ('INVENTARIO_NO_REALIZADO', 'Inventario no realizado'), ('INVENTARIO_INCOMPLETO', 'Inventario incompleto'), ('INVENTARIO_SIN_FINALIZAR', 'Inventario sin finalizar'), ('INVENTARIO_REABIERTO', 'Inventario reabierto'), ('INVENTARIO_ANULADO', 'Inventario anulado')], default='INVENTARIO_INCOMPLETO', max_length=35)),
                ('level', models.CharField(choices=[('INFORMATIVA', 'Informativa'), ('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=15)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('state', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida')], default='PENDIENTE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_comment', models.TextField(blank=True)),
                ('attended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_attended', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventarios.inventory')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventarios.inventoryitem')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='inventarios.pointofsale')),
            ],
            options={
                'ordering': ['attended', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('PUNTO_VENTA', 'Punto de venta')], max_length=20, verbose_name='rol')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='inventarios.pointofsale', verbose_name='punto de venta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'ANULADO'), _negated=True), fields=('point', 'inventory_date', 'inventory_type'), name='unique_active_inventory_per_point_date_type'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('inventory', 'product'), name='unique_product_per_inventory'),
        ),
    ]
