from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
import django.utils.timezone
class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
    migrations.CreateModel(name='AppSetting',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('daily_deadline',models.TimeField(default='21:00')),('general_frequency_days',models.PositiveIntegerField(default=7)),('general_deadline',models.TimeField(default='21:00')),('require_observation_on_alert',models.BooleanField(default=True)),('updated_at',models.DateTimeField(auto_now=True))]),
    migrations.CreateModel(name='Product',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120,unique=True)),('code',models.CharField(max_length=30,unique=True)),('category',models.CharField(blank=True,max_length=80)),('unit',models.CharField(default='Unidad',max_length=30)),('active',models.BooleanField(default=True)),('include_daily',models.BooleanField(default=False)),('include_general',models.BooleanField(default=True)),('allows_decimals',models.BooleanField(default=True)),('critical_qty',models.DecimalField(blank=True,decimal_places=2,max_digits=12,null=True,validators=[django.core.validators.MinValueValidator(0)])),('minimum_qty',models.DecimalField(blank=True,decimal_places=2,max_digits=12,null=True,validators=[django.core.validators.MinValueValidator(0)])),('maximum_qty',models.DecimalField(blank=True,decimal_places=2,max_digits=12,null=True,validators=[django.core.validators.MinValueValidator(0)])),('display_order',models.PositiveIntegerField(default=100)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True))],options={'ordering':['display_order','category','name']}),
    migrations.CreateModel(name='Profile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('role',models.CharField(choices=[('ADMIN','Administrador'),('POS','Punto de venta')],max_length=10)),('point_name',models.CharField(default='La Central',max_length=80)),('active',models.BooleanField(default=True)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='profile',to=settings.AUTH_USER_MODEL))]),
    migrations.CreateModel(name='Inventory',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('inventory_type',models.CharField(choices=[('DAILY','Inventario diario'),('GENERAL','Inventario general')],max_length=10)),('inventory_date',models.DateField(default=django.utils.timezone.localdate)),('point_name',models.CharField(default='La Central',max_length=80)),('state',models.CharField(choices=[('DRAFT','Borrador'),('FINAL','Finalizado'),('FINAL_ALERT','Finalizado con alertas'),('CANCELLED','Anulado')],default='DRAFT',max_length=20)),('started_at',models.DateTimeField(auto_now_add=True)),('finalized_at',models.DateTimeField(blank=True,null=True)),('general_observation',models.TextField(blank=True)),('total_expected',models.PositiveIntegerField(default=0)),('total_counted',models.PositiveIntegerField(default=0)),('total_critical',models.PositiveIntegerField(default=0)),('total_low',models.PositiveIntegerField(default=0)),('total_normal',models.PositiveIntegerField(default=0)),('total_high',models.PositiveIntegerField(default=0)),('created_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='inventories_created',to=settings.AUTH_USER_MODEL))],options={'ordering':['-inventory_date','-started_at']}),
    migrations.CreateModel(name='InventoryItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('product_code',models.CharField(max_length=30)),('product_name',models.CharField(max_length=120)),('category',models.CharField(blank=True,max_length=80)),('unit',models.CharField(max_length=30)),('quantity',models.DecimalField(blank=True,decimal_places=2,max_digits=12,null=True,validators=[django.core.validators.MinValueValidator(0)])),('critical_applied',models.DecimalField(blank=True,decimal_places=2,max_digits=12,null=True)),('minimum_applied',models.DecimalField(blank=True,decimal_places=2,max_digits=12,null=True)),('maximum_applied',models.DecimalField(blank=True,decimal_places=2,max_digits=12,null=True)),('result',models.CharField(choices=[('CRITICAL','Crítico'),('LOW','Bajo'),('NORMAL','Normal'),('HIGH','Alto'),('NO_RULE','Sin regla'),('NOT_COUNTED','No contado')],default='NOT_COUNTED',max_length=20)),('observation',models.TextField(blank=True)),('updated_at',models.DateTimeField(auto_now=True)),('inventory',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='inventarios.inventory')),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='inventarios.product'))],options={'ordering':['product__display_order','product_name'],'unique_together':{('inventory','product')}}),
    migrations.CreateModel(name='Alert',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('alert_date',models.DateField(default=django.utils.timezone.localdate)),('title',models.CharField(max_length=160)),('message',models.TextField()),('level',models.CharField(choices=[('INFO','Informativa'),('MEDIUM','Media'),('HIGH','Alta'),('CRITICAL','Crítica')],max_length=10)),('resolved',models.BooleanField(default=False)),('resolved_at',models.DateTimeField(blank=True,null=True)),('resolution_note',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('inventory',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='alerts',to='inventarios.inventory')),('resolved_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='alerts_resolved',to=settings.AUTH_USER_MODEL))],options={'ordering':['resolved','-created_at']}),
    migrations.AddConstraint(model_name='inventory',constraint=models.UniqueConstraint(condition=models.Q(('state__in',['DRAFT','FINAL','FINAL_ALERT'])),fields=('point_name','inventory_date','inventory_type'),name='unique_active_inventory_per_day_type'))]
