# Generated by Django 5.2.16 on 2026-07-28 03:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_values(apps, schema_editor):
    PointOfSale = apps.get_model("inventarios", "PointOfSale")
    Profile = apps.get_model("inventarios", "Profile")
    Inventory = apps.get_model("inventarios", "Inventory")
    InventoryItem = apps.get_model("inventarios", "InventoryItem")
    Alert = apps.get_model("inventarios", "Alert")
    point, _ = PointOfSale.objects.get_or_create(
        code="CENTRAL",
        defaults={"name": "La Central", "active": True},
    )
    Profile.objects.filter(role="POS").update(role="PUNTO_VENTA")
    Profile.objects.filter(point__isnull=True).update(point=point)
    type_map = {"DAILY": "DIARIO"}
    state_map = {
        "DRAFT": "BORRADOR",
        "FINAL": "FINALIZADO",
        "FINAL_ALERT": "FINALIZADO_CON_ALERTAS",
        "CANCELLED": "ANULADO",
    }
    result_map = {
        "CRITICAL": "CRITICO",
        "LOW": "BAJO",
        "HIGH": "ALTO",
        "NO_RULE": "SIN_REGLA",
        "NOT_COUNTED": "NO_CONTADO",
    }
    for old, new in type_map.items():
        Inventory.objects.filter(inventory_type=old).update(inventory_type=new)
    for old, new in state_map.items():
        Inventory.objects.filter(state=old).update(state=new)
    for old, new in result_map.items():
        InventoryItem.objects.filter(result=old).update(result=new)
    for inventory in Inventory.objects.filter(point__isnull=True):
        inventory.point = point
        inventory.responsible_id = inventory.created_by_id
        inventory.modified_by_id = inventory.created_by_id
        inventory.locked = inventory.state in ["FINALIZADO", "FINALIZADO_CON_ALERTAS", "ANULADO"]
        inventory.save(
            update_fields=["point", "responsible", "modified_by", "locked"]
        )
    for alert in Alert.objects.filter(point__isnull=True).select_related("inventory"):
        if alert.inventory_id:
            alert.point_id = alert.inventory.point_id
            alert.save(update_fields=["point"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('CREAR_INVENTARIO', 'Crear inventario'), ('GUARDAR_BORRADOR', 'Guardar borrador'), ('FINALIZAR_INVENTARIO', 'Finalizar inventario'), ('REABRIR_INVENTARIO', 'Reabrir inventario'), ('EDITAR_INVENTARIO', 'Editar inventario'), ('ANULAR_INVENTARIO', 'Anular inventario'), ('CREAR_PRODUCTO', 'Crear producto'), ('EDITAR_PRODUCTO', 'Editar producto'), ('ACTIVAR_PRODUCTO', 'Activar producto'), ('DESACTIVAR_PRODUCTO', 'Desactivar producto'), ('CAMBIAR_REGLAS', 'Cambiar reglas'), ('ATENDER_ALERTA', 'Atender alerta'), ('CAMBIAR_CONFIGURACION', 'Cambiar configuración')], max_length=30)),
                ('model', models.CharField(max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('daily_deadline', models.TimeField(default='21:00', verbose_name='hora límite inventario diario')),
                ('general_deadline', models.TimeField(default='21:00', verbose_name='hora límite inventario general')),
                ('general_frequency', models.CharField(choices=[('DIARIO', 'Diaria'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='SEMANAL', max_length=15, verbose_name='frecuencia inventario general')),
            ],
            options={
                'verbose_name': 'punto de venta',
                'verbose_name_plural': 'puntos de venta',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['attended', '-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='inventory',
            name='unique_active_inventory_per_day_type',
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='alert',
            name='alert_date',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='resolution_note',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='resolved',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='appsetting',
            name='daily_deadline',
        ),
        migrations.RemoveField(
            model_name='appsetting',
            name='general_deadline',
        ),
        migrations.RemoveField(
            model_name='appsetting',
            name='general_frequency_days',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='point_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='point_name',
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('PRODUCTO_CRITICO', 'Producto crítico'), ('PRODUCTO_BAJO', 'Producto bajo'), ('PRODUCTO_ALTO', 'Producto alto'), ('INVENTARIO_NO_REALIZADO', 'Inventario no realizado'), ('INVENTARIO_INCOMPLETO', 'Inventario incompleto'), ('INVENTARIO_SIN_FINALIZAR', 'Inventario sin finalizar'), ('INVENTARIO_REABIERTO', 'Inventario reabierto'), ('INVENTARIO_ANULADO', 'Inventario anulado')], default='INVENTARIO_INCOMPLETO', max_length=35),
        ),
        migrations.AddField(
            model_name='alert',
            name='attendance_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='attended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='attended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_attended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventarios.inventoryitem'),
        ),
        migrations.AddField(
            model_name='alert',
            name='state',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida')], default='PENDIENTE', max_length=12),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='generate_product_alerts',
            field=models.BooleanField(default=True, verbose_name='generar alertas por producto'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='bloqueado'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories_reopened', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories_responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items_registered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='require_observation_high_applied',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='require_observation_low_applied',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='require_observation_high',
            field=models.BooleanField(default=True, verbose_name='exigir observación en alto'),
        ),
        migrations.AddField(
            model_name='product',
            name='require_observation_low',
            field=models.BooleanField(default=True, verbose_name='exigir observación en crítico o bajo'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='level',
            field=models.CharField(choices=[('INFORMATIVA', 'Informativa'), ('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=15),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='require_observation_on_alert',
            field=models.BooleanField(default=True, verbose_name='exigir observación según la regla del producto'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='finalización'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='general_observation',
            field=models.TextField(blank=True, verbose_name='observación general'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de inventario'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('DIARIO', 'Inventario diario'), ('GENERAL', 'Inventario general')], max_length=15, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='inicio'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='state',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_PROGRESO', 'En progreso'), ('FINALIZADO', 'Finalizado'), ('FINALIZADO_CON_ALERTAS', 'Finalizado con alertas'), ('REABIERTO', 'Reabierto'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=30, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, max_length=80, verbose_name='categoría snapshot'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='product_code',
            field=models.CharField(max_length=30, verbose_name='código snapshot'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='product_name',
            field=models.CharField(max_length=120, verbose_name='nombre snapshot'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cantidad contada'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='result',
            field=models.CharField(choices=[('CRITICO', 'Crítico'), ('BAJO', 'Bajo'), ('NORMAL', 'Normal'), ('ALTO', 'Alto'), ('SIN_REGLA', 'Sin regla'), ('NO_CONTADO', 'No contado')], default='NO_CONTADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(max_length=30, verbose_name='unidad snapshot'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allows_decimals',
            field=models.BooleanField(default=True, verbose_name='permite decimales'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=80, verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='product',
            name='critical_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cantidad crítica'),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_order',
            field=models.PositiveIntegerField(default=100, verbose_name='orden visual'),
        ),
        migrations.AlterField(
            model_name='product',
            name='include_daily',
            field=models.BooleanField(default=False, verbose_name='incluir en inventario diario'),
        ),
        migrations.AlterField(
            model_name='product',
            name='include_general',
            field=models.BooleanField(default=True, verbose_name='incluir en inventario general'),
        ),
        migrations.AlterField(
            model_name='product',
            name='maximum_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cantidad máxima'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cantidad mínima'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=30, verbose_name='unidad de medida'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('PUNTO_VENTA', 'Punto de venta')], max_length=20, verbose_name='rol'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('inventory', 'product'), name='unique_product_per_inventory'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='inventarios.pointofsale'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='inventarios.pointofsale'),
        ),
        migrations.AddField(
            model_name='profile',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='inventarios.pointofsale', verbose_name='punto de venta'),
        ),
        migrations.RunPython(migrate_legacy_values, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'ANULADO'), _negated=True), fields=('point', 'inventory_date', 'inventory_type'), name='unique_active_inventory_per_point_date_type'),
        ),
    ]
